Added more information about the Fabric version
LuckPerms/wiki pull request #116
Opened 2021-04-09 12:51 UTC by LeotomasMC

Includes the different configuration location on Sponge and Fabric on the installation page, and replaces "the plugin" in contexts that it could refer to either LuckPerms as a plugin *or* LuckPerms as a mod.

2021-04-09 17:13 UTC, Fefo6644 commented
> this part could probably be handled better, as on Fabric (and possibly sponge as well, but didnt test), the config and translations are in `./config/LuckPerms/` while the database is in `./mods/luckperms/`. Either this part of the guide could be rewritten to show these differences, or they could be all moved to the same place in LuckPerms itself.

Haven't tested this myself but they *should* be in the correct `./config/luckperms` folder now
https://github.com/lucko/LuckPerms/commit/327ccec02f1779ba5a1fa9430633e2deff24fec0

2021-04-09 17:15 UTC, Fefo6644 requested changes

2021-04-09 17:15 UTC, Fefo6644 commented on pages/Installation.md
> +You can click the "edit" button next to `config.yml` (or `luckperms.conf`) to open an editor in your browser. It's also possible to edit these files via FTP.
```suggestion
You can click the "edit" button next to `config.yml` or `luckperms.conf` to open an editor in your browser. It's also possible to edit these files via FTP.
```

2021-04-09 17:15 UTC, Fefo6644 commented on pages/Installation.md
> +Here you will find a number of files. The important ones are:
```suggestion
Here you will find a number of files. The important ones are:
```

2021-04-09 17:15 UTC, Fefo6644 commented on pages/FAQ.md
> +If you are running a Fabric server with LuckPerms, you **cannot use permissions with vanilla commands**. Unlike Bukkit and Spigot, Fabric does not add permission checks for vanilla commands. Also not
```suggestion
If you are running a Fabric server with LuckPerms, you **cannot use permissions with vanilla commands**. Unlike Bukkit/Spigot and Sponge, Fabric does not add permission checks for vanilla commands. This is not an issue with LuckPerms and it's something that may change in the future.

Also note that individual mods may not support permissions either, as permissions in Fabric are not yet as standardized as they are in Bukkit/Spigot or Sponge.
```

2021-04-09 17:15 UTC, Fefo6644 commented on pages/Installation.md
> +However, if you would prefer for LuckPerms data to be stored in **readable, editable .yml files**: open `config.yml` (or `luckperms.conf`), scroll down to the "Storage Settings" section and set `stor
```suggestion
However, if you would prefer for LuckPerms data to be stored in **readable, editable .yml files**: open `config.yml`/`luckperms.conf`, scroll down to the "Storage Settings" section and set `storage-method` to `yaml`. Then restart your server.
```

2021-04-09 17:15 UTC, Fefo6644 commented on pages/Installation.md
> +Once you have these details, take a note of them (or duplicate your tab), then navigate back to the LuckPerms `config.yml` (or `luckperms.conf`) file in the File Manager, and click "edit".
```suggestion
Once you have these details, take a note of them (or duplicate your tab), then navigate back to the LuckPerms `config.yml`/`luckperms.conf` file in the File Manager, and click "edit".
```

2021-04-27 20:20 UTC, Laarryy approved these changes
Looks real good to me. Thank you very much for contributing!

2021-04-27 20:22 UTC, Fefo6644 approved these changes
Larry got back from hibernation it seems 😆

2021-04-27 20:24 UTC, merged