Improve GM-&-PEX-Command-Equivalents.md
LuckPerms/wiki pull request #14
Opened 2019-07-25 14:04 UTC by Andre601

## Changes
```diff
- lp verbose true
+ lp verbose <option> # Also added relative link to verbose page (../verbose)

~ Link to Default assignment section in wiki (../Default-Groups#configure-default-assignments)

- lp <user|group> permission <settemp|set> <permission> true global <world>
+ lp <user|group> permission <settemp|set> <permission> <true/false> world=<world>

~ Changed settemp command to unsettemp where PEX has timed remove
```

2019-07-30 11:59 UTC, Andre601 commented
New changes being added:
```diff
+ Added link to Web editor page at the end of Web Editor section in "Why LuckPerms"
+ Added section about version and platform support of LuckPerms in "Why LuckPerms"
```

2019-07-30 12:05 UTC, Andre601 commented
Changed relative links (`../[page]#[section]`) to normal (full) links

2019-08-26 19:46 UTC, Tobi406 requested changes

2019-08-26 19:46 UTC, Tobi406 commented on Why-LuckPerms.md
> +For older versions or different platforms (BungeeCord, Velocity, Sponge) does LuckPerms have alternative downloads available on its [website](https://luckperms.github.io).
NukkitX missing

2019-08-26 20:15 UTC, Andre601 commented on Why-LuckPerms.md
> +For older versions or different platforms (BungeeCord, Velocity, Sponge) does LuckPerms have alternative downloads available on its [website](https://luckperms.github.io).
Fixed.

2019-08-26 20:16 UTC, Andre601 commented
```diff
- Note about PEX being discontinued (and suggests LP)
~ Changed link of LP website to https://luckperms.net
```

2019-08-26 20:18 UTC, Tobi406 approved these changes

2019-08-26 20:24 UTC, Andre601 commented
```diff
- Link to default assignment since it will be removed/replaced in v5
```

2019-10-02 12:10 UTC, merged

2019-10-02 12:12 UTC, Andre601 commented
Just wait with updating the main wiki as V5 isn't out yet ;)